export const AUTH_IS_AUTHENTICATED = 'IS_AUTHENTICATED'
// interivewset
export const INTERVIEWSET_LIST = 'INTERVIEWSET_LIST'
export const INTERVIEWSET_NAME = 'INTERVIEWSET_NAME'
export const INTERVIEWSET_TAGS = 'INTERVIEWSET_TAGS'
// export const INTERVIEWSET_TAG = 'INTERVIEWSET_TAG'
export const INTERVIEWSET_TAG_QUESTIONS = 'INTERVIEWSET_TAG_QUESTIONS'
// question
export const QM_JOB_QUESTION = 'QM_JOB_QUESTION'
export const QM_QUESTION_LIST = 'QM_QUESTION_LIST'
