export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
// Question Manage
export const QM_LIST = 'QM_LIST'
export const QM_DETAILS = 'QM_DETAILS'
// Interviewset
export const INTERVIEWSET_INIT = 'INTERVIEWSET_INIT'
export const INTERVIEWSET_UPDATE_NAME = 'INTERVIEWSET_UPDATE_NAME'
export const INTERVIEWSET_ADD_TAG = 'INTERVIEWSET_ADD_TAG'
export const INTERVIEWSET_UPDATE_SELECTED_TAG = 'INTERVIEWSET_UPDATE_SELECTED_TAG'
export const INTERVIEWSET_UPDATE_TAG_QUESTION = 'INTERVIEWSET_UPDATE_TAG_QUESTION'
